name: Generate Dev Stats Cards

on:
    schedule:
        - cron: '0 20 * * *'
    workflow_dispatch:

jobs:
    build-and-update:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Generate GitHub stats card
              uses: readme-tools/github-readme-stats-action@v1
              with:
                  card: stats
                  options: username=${{ github.repository_owner }}&hide_title=true&hide_border=true&show_icons=true&rank_icon=github&include_all_commits=true&count_private=true&line_height=22&theme=nightowl
                  path: assets/stats.svg
                  token: ${{ secrets.DEV_STATS_TOKEN }}

            - name: Generate GitHub top languages card
              uses: readme-tools/github-readme-stats-action@v1
              with:
                  card: top-langs
                  options: username=${{ github.repository_owner }}&hide=html&hide_title=true&hide_border=true&layout=compact&langs_count=8&theme=nightowl
                  path: assets/top-langs.svg
                  token: ${{ secrets.DEV_STATS_TOKEN }}

            - name: Update cards
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

                  git add assets/*.svg
                  git commit -m "Update dev stats cards" || exit 0
                  git push
